name: MuleSoft CD process script

# Trigger settings
on:
  workflow_dispatch:
    inputs:
      org:
        description: 'Deploy Environment.'
        required: true
        default: 'SalesDept'
      env:
        description: 'Deploy Bussines group.'
        required: false
        default: 'Dev'

# Job settings
jobs:
  # build script
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Echo input parameter.
        run: |
          echo "Hello ${{ github.event.inputs.name }}!"
          echo "- in ${{ github.event.inputs.home }}!"
      
      - name: Upload the Mule application file to the release folder.
        run: java -jar app.jar -gitrelease -org ${{ github.event.inputs.org }}! -env ${{ github.event.inputs.env }}!
        shell: bash
        working-directory: .github/script