# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CloudHubのビルドスクリプト

# トリガーの設定
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# ジョブの設定
jobs:
  # ビルドスクリプト
  build:
    # 仮想環境
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: deploy.sh
      shell: bash
      working-directory: ./github/script
      # run: mvn -B package --file pom.xml
